import { useEffect, useState, type ReactNode } from 'react'
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronDown, Code2, Copy, Download, Info, LockKeyhole, Radio, RefreshCw, ShieldCheck, SlidersHorizontal, Sparkles, Wallet } from 'lucide-react'
import { canonicalManifest, compileIntent, validateManifest, type StrategyManifest } from '../../lib/strategy'
import { manifestHash } from '../../lib/contracts/engine'
import type { LocalDraft } from '../../lib/workspace'
import { useMarket, type Circuit } from '../../hooks/useCircuit'
import { ActivationDialog } from '../ActivationDialog'
import { Modal, Pill, Spinner, StrategyFlow, type RuleSection } from './shared'
const steps:{id:RuleSection;label:string;hint:string}[]=[{id:'market',label:'Market',hint:'Choose your playing field'},{id:'entry',label:'Entry rule',hint:'Decide when to act'},{id:'risk',label:'Boundaries',hint:'Make your limits clear'},{id:'review',label:'Review',hint:'Your rules, all together'}]
function Field({label,hint,error,children}:{label:string;hint?:string;error?:string;children:ReactNode}){return <label className={`field ${error?'field-invalid':''}`}><span>{label}</span>{children}{error?<small className="field-error">{error}</small>:hint&&<small>{hint}</small>}</label>}
export default function Builder({draft,onSave,circuit,onBack,onActivated,onDirty}:{draft:LocalDraft;onSave:(draft:LocalDraft)=>void;circuit:Circuit;onBack:()=>void;onActivated:()=>void;onDirty:(dirty:boolean)=>void}){
 const [manifest,setManifest]=useState<StrategyManifest>(()=>structuredClone(draft.manifest))
 const [step,setStep]=useState<RuleSection>('market')
 const [saved,setSaved]=useState(true)
 const [showJson,setShowJson]=useState(false)
 const [showCompiler,setShowCompiler]=useState(false)
 const [prompt,setPrompt]=useState('If BTC 15m UP trades above 70%, buy DOWN with 10. Roll half after a win and stop after two losses. Never risk more than 20. Max 5 rounds, slippage 200 bps, expiry buffer 120 seconds.')
 const [compilerErrors,setCompilerErrors]=useState<string[]>([])
 const [activationOpen,setActivationOpen]=useState(false)
 const [showErrors,setShowErrors]=useState(false)
 const market=useMarket(manifest)
 const issues=validateManifest(manifest)
 const index=steps.findIndex(item=>item.id===step)
 useEffect(()=>{onDirty(!saved);const before=(e:BeforeUnloadEvent)=>{if(!saved)e.preventDefault()};window.addEventListener('beforeunload',before);return()=>{onDirty(false);window.removeEventListener('beforeunload',before)}},[saved,onDirty])
 const edit=(patch:Partial<StrategyManifest>)=>{const next={...manifest,...patch};setManifest(next);setSaved(false);if(!validateManifest(next).length){try{onSave({...draft,manifest:next,updatedAt:new Date().toISOString()});setSaved(true)}catch{circuit.toast('Changes could not be saved in this browser. Export your manifest before leaving.','error')}}}
 const error=(path:string)=>showErrors?issues.find(item=>item.path===path)?.message:undefined
 const numeric=(value:number)=>Number.isFinite(value)?value:''
 const number=(value:string)=>value===''?NaN:Number(value)
 const download=()=>{if(issues.length){setShowErrors(true);circuit.toast('Complete the missing fields before exporting.','error');return}const url=URL.createObjectURL(new Blob([canonicalManifest(manifest)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`circuit-${draft.id.slice(0,8)}.json`;a.click();URL.revokeObjectURL(url);circuit.toast('Manifest exported.','success')}
 const copy=async()=>{try{await navigator.clipboard.writeText(canonicalManifest(manifest));circuit.toast('Manifest copied to clipboard.','success')}catch{circuit.toast('Clipboard unavailable. Use Download instead.','error')}}
 const next=()=>{setShowErrors(true);if(index===2&&issues.length){circuit.toast('A few boundaries need your attention.','error');return}setStep(steps[Math.min(index+1,3)].id)}
 const review=()=>{setShowErrors(true);if(issues.length){setStep('risk');return}if(!circuit.wallet){void circuit.connect();return}if(!circuit.walletConnected){void circuit.switchNetwork();return}if(market.status!=='ready'){circuit.toast('An eligible trading window must be verified first. Refresh market availability.','error');return}setActivationOpen(true)}
 const compile=()=>{const candidate=compileIntent(prompt);const invalid=validateManifest(candidate);setCompilerErrors(invalid.map(item=>item.message));if(invalid.length)return;edit(candidate as StrategyManifest);setShowCompiler(false);setStep('review');circuit.addActivity('Intent compiled','A complete local draft is ready for your review. No transaction was sent.');circuit.toast('Your idea is now a draft. Review each rule.','success')}
 const canActivate=!(circuit.session&&circuit.runtime&&![8,9].includes(circuit.runtime.status))
 return <><div className="builder-heading"><div className="builder-heading-main"><button className="icon-btn" onClick={onBack} aria-label="Back to strategies"><ArrowLeft size={19}/></button><div><div className="eyebrow">STRATEGY STUDIO</div><input className="strategy-title-input" aria-label="Strategy name" value={manifest.name} onChange={e=>edit({name:e.target.value})}/></div></div><div className="builder-heading-actions"><span className={`save-status ${saved?'saved':''}`}>{saved?<CheckCheck size={14}/>:<Info size={14}/>} {saved?'Saved in this browser':'Unsaved changes'}</span><button className="btn btn-white btn-sm" onClick={()=>setShowCompiler(true)}><Sparkles size={15}/> Start with an idea</button><button className="icon-btn" aria-label="View strategy manifest" onClick={()=>setShowJson(true)}><Code2 size={19}/></button></div></div>
 <div className="studio-steps" aria-label="Strategy builder steps">{steps.map((item,i)=><button key={item.id} className={step===item.id?'active':i<index?'complete':''} onClick={()=>{if(item.id==='review'&&issues.length){setShowErrors(true);circuit.toast('Complete your rules before review.','error');return}setStep(item.id)}} aria-current={step===item.id?'step':undefined}><span>{i<index?<Check size={13}/>:String(i+1).padStart(2,'0')}</span>{item.label}<ArrowRight size={14}/></button>)}</div>
 <div className="studio-layout"><section className="studio-canvas"><div className="canvas-heading"><div><span className="eyebrow">YOUR CIRCUIT</span><p>A clear path from idea to action.</p></div><Pill>Draft preview</Pill></div><StrategyFlow manifest={manifest} selected={step} onSelect={setStep}/><div className="canvas-footer"><span><LockKeyhole size={13}/> Every branch respects your limits</span><span>v1 · structured rules</span></div></section>
 <section className="inspector" aria-label={`${steps[index].label} configuration`}><header className="inspector-heading"><span className="eyebrow">STEP {index+1} OF 4</span><h2>{steps[index].hint}<span>.</span></h2><p>{step==='market'?'Find an event market that fits your strategy.':step==='entry'?'A verified fill checks your condition. You decide the response.':step==='risk'?'These limits become part of the strategy you authorize.':'Read it once. Make sure it feels like your plan.'}</p></header>
 <div className="inspector-body" key={step}>
 {step==='market'&&<><Field label="Underlying asset"><div className="choice-grid">{(['BTC','ETH'] as const).map(asset=><button type="button" className={`choice asset-choice ${manifest.series.asset===asset?'selected':''}`} key={asset} aria-pressed={manifest.series.asset===asset} onClick={()=>edit({series:{...manifest.series,asset}})}><span className={`coin-icon ${asset==='ETH'?'eth':''}`}>{asset==='BTC'?'₿':'Ξ'}</span><span><strong>{asset==='BTC'?'Bitcoin':'Ethereum'}</strong><small>{asset}</small></span>{manifest.series.asset===asset&&<Check size={15}/>}</button>)}</div></Field><Field label="Market window" hint="A new market opens for each supported window."><div className="choice-grid">{([900,3600] as const).map(intervalSec=><button key={intervalSec} type="button" className={`choice cadence-choice ${manifest.series.intervalSec===intervalSec?'selected':''}`} aria-pressed={manifest.series.intervalSec===intervalSec} onClick={()=>edit({series:{...manifest.series,intervalSec}})}><strong>{intervalSec===900?'15 minutes':'1 hour'}</strong><small>{intervalSec===900?'A shorter horizon':'Room to develop'}</small></button>)}</div></Field><div className={`market-check ${market.status}`} aria-live="polite"><div>{market.status==='loading'?<Spinner label="Finding a trading window"/>:market.status==='ready'?<><Check size={16}/><strong>Trading window verified</strong></>:<><Info size={16}/><strong>{market.errorKind==='unavailable'?'No eligible window found':'Could not verify market'}</strong></>}<button className="icon-btn" onClick={market.retry} disabled={market.status==='loading'} aria-label="Refresh market availability"><RefreshCw size={14}/></button></div>{market.status==='loading'?<><p>Reading market discovery and current chain state.</p><div className="skeleton"/><div className="skeleton short"/></>:market.market?<><p>{market.market.question}</p><small>Closes {new Date(market.market.expiry*1000).toLocaleTimeString('en-GB')} · block {String(market.market.blockNumber)}</small><a href={`https://shannon-explorer.somnia.network/address/${market.market.marketAddress}`} target="_blank" rel="noreferrer">Inspect market <ArrowUpRight size={13}/></a></>:<><p>{market.errorKind==='unavailable'?`No eligible ${manifest.series.asset} ${manifest.series.intervalSec===900?'15 minute':'1 hour'} trading window was found with at least ${manifest.policy.minSecondsToExpiry}s remaining. Choose another asset or duration, or refresh later. You can keep editing your draft.`:'Market verification failed because the connection or market service could not complete the request. Retry to check availability; your draft is saved.'}</p><details><summary>{market.errorKind==='unavailable'?'Availability details':'Connection details'}</summary><p>{market.error}</p></details></>}</div><div className="field-note"><Radio size={16}/><p>We verify the actual market before activation. A sample graph never places an order.</p></div></>}
 {step==='entry'&&<><Field label="When the UP fill price is"><div className="segmented">{(['LAST_FILL_PRICE_ABOVE','LAST_FILL_PRICE_BELOW'] as const).map(type=><button key={type} aria-pressed={manifest.trigger.type===type} className={manifest.trigger.type===type?'active':''} onClick={()=>edit({trigger:{...manifest.trigger,type}})}>{type==='LAST_FILL_PRICE_ABOVE'?'Above threshold':'Below threshold'}</button>)}</div></Field><Field label="Trigger probability" hint="Compared against a real UP fill, not an estimated price." error={error('trigger.value')}><div className="input-unit"><input aria-label="Trigger probability" inputMode="decimal" type="number" min="0" max="100" step="0.1" value={manifest.trigger.value===''?'':Number(manifest.trigger.value)*100} onChange={e=>edit({trigger:{...manifest.trigger,value:e.target.value===''?'':String(Number(e.target.value)/100)}})}/><span>% UP</span></div></Field><Field label="Then place this order"><div className="choice-grid">{(['BUY_UP','BUY_DOWN'] as const).map(type=><button className={`choice direction-choice ${manifest.action.type===type?'selected':''}`} key={type} aria-pressed={manifest.action.type===type} onClick={()=>edit({action:{...manifest.action,type}})}><ArrowUpRight size={20} className={type==='BUY_DOWN'?'rotate-down':''}/><strong>{type==='BUY_UP'?'Buy UP':'Buy DOWN'}</strong></button>)}</div></Field><Field label="Maximum order size" hint="The most this strategy can spend on one order. Up to 10 tUSDC." error={error('action.maxCollateral')}><div className="input-unit"><input aria-label="Maximum order size" type="number" inputMode="decimal" min="0.000001" max="10" step="0.1" value={manifest.action.maxCollateral} onChange={e=>edit({action:{...manifest.action,maxCollateral:e.target.value}})}/><span>tUSDC</span></div></Field><div className="field-note"><Info size={16}/><p>Orders fill immediately within your limit. Unfilled quantity does not stay on the book.</p></div></>}
 {step==='risk'&&<><Field label="Lifetime spending cap" hint="Cumulative spending across all rounds. Redeeming does not reset this cap." error={error('policy.maxTotalCapitalAtRisk')}><div className="input-unit"><input aria-label="Lifetime spending cap" type="number" inputMode="decimal" min="0" value={manifest.policy.maxTotalCapitalAtRisk} onChange={e=>edit({policy:{...manifest.policy,maxTotalCapitalAtRisk:e.target.value}})}/><span>tUSDC</span></div></Field><div className="field-pair"><Field label="Maximum rounds" error={error('policy.maxRounds')}><input aria-label="Maximum rounds" type="number" min="1" max="65535" value={numeric(manifest.policy.maxRounds)} onChange={e=>edit({policy:{...manifest.policy,maxRounds:number(e.target.value)}})}/></Field><Field label="Stop after losses" error={error('policy.stopAfterConsecutiveLosses')}><input aria-label="Stop after losses" type="number" min="1" value={numeric(manifest.policy.stopAfterConsecutiveLosses)} onChange={e=>edit({policy:{...manifest.policy,stopAfterConsecutiveLosses:number(e.target.value)}})}/></Field></div><Field label="Roll after a win" hint="Percentage of redeemed proceeds allocated to the next order, within your caps." error={error('resolution.onWin.rollPercent')}><div className="input-unit"><input aria-label="Roll after a win" type="number" min="0" max="100" value={numeric(manifest.resolution.onWin.rollPercent)} onChange={e=>edit({resolution:{...manifest.resolution,onWin:{rollPercent:number(e.target.value)}}})}/><span>%</span></div></Field><div className="field-pair"><Field label="Slippage limit" hint="100 bps = 1%" error={error('action.maxSlippageBps')}><div className="input-unit"><input aria-label="Slippage limit" type="number" min="0" max="1000" value={numeric(manifest.action.maxSlippageBps)} onChange={e=>edit({action:{...manifest.action,maxSlippageBps:number(e.target.value)}})}/><span>bps</span></div></Field><Field label="Expiry buffer" hint="Minimum time to close" error={error('policy.minSecondsToExpiry')}><div className="input-unit"><input aria-label="Expiry buffer" type="number" min="1" value={numeric(manifest.policy.minSecondsToExpiry)} onChange={e=>edit({policy:{...manifest.policy,minSecondsToExpiry:number(e.target.value)}})}/><span>sec</span></div></Field></div><div className="field-note"><ShieldCheck size={17}/><p>Consecutive losses count toward your stop rule. Void and skipped rounds stay neutral.</p></div></>}
 {step==='review'&&<><div className="review-sentence">When <b>{manifest.series.asset}</b> UP trades <b>{manifest.trigger.type==='LAST_FILL_PRICE_ABOVE'?'above':'below'} {Number(manifest.trigger.value)*100}%</b>, buy <b>{manifest.action.type==='BUY_UP'?'UP':'DOWN'}</b> with at most <b>{manifest.action.maxCollateral} tUSDC.</b></div><dl className="review-limits"><div><dt>Lifetime spending</dt><dd>{manifest.policy.maxTotalCapitalAtRisk} tUSDC</dd></div><div><dt>Round limit</dt><dd>{manifest.policy.maxRounds} rounds</dd></div><div><dt>Consecutive loss stop</dt><dd>{manifest.policy.stopAfterConsecutiveLosses} losses</dd></div><div><dt>Win allocation</dt><dd>{manifest.resolution.onWin.rollPercent}% of proceeds</dd></div><div><dt>Slippage / expiry buffer</dt><dd>{manifest.action.maxSlippageBps} bps / {manifest.policy.minSecondsToExpiry}s</dd></div></dl><div className="review-checks"><span><Check size={15}/> Complete, finite risk boundaries</span><span>{market.status==='ready'?<Check size={15}/>:<Info size={15}/>} {market.status==='ready'?'Live market verified':'Market availability needs a check'}</span><span>{circuit.walletConnected?<Check size={15}/>:<Wallet size={15}/>} {circuit.walletConnected?'Wallet connected on Shannon':'Connect your wallet to authorize'}</span></div><div className="field-note"><LockKeyhole size={17}/><p>Activation locks these rules and authorizes bounded next-window approvals. Automatic execution requires a running keeper.</p></div>{!canActivate&&<div className="inline-warning">An on-chain strategy is already linked to this workspace. This draft is saved separately; manage the existing strategy from Activity before activating another.</div>}<button className="text-link" onClick={()=>setShowJson(true)}>Inspect the exact manifest <Code2 size={14}/></button></>}
 {showErrors&&issues.length>0&&<div className="inline-warning" role="alert">{issues.length} field{issues.length>1?'s':''} need attention. {issues[0].message}</div>}
 </div><footer className="inspector-footer">{index>0&&<button className="btn btn-white" onClick={()=>setStep(steps[index-1].id)}><ArrowLeft size={15}/> Back</button>}{step==='review'?<button className="btn btn-primary" disabled={!canActivate||!!issues.length||circuit.walletBusy||(circuit.walletConnected&&market.status!=='ready')} onClick={review}>{circuit.walletBusy?<Spinner label="Connecting"/>:!circuit.wallet?'Connect wallet':!circuit.walletConnected?'Switch to Shannon':'Review & activate'}<ArrowUpRight size={16}/></button>:<button className="btn btn-primary" onClick={next}>Continue <ArrowRight size={16}/></button>}</footer></section></div>
 {showJson&&<Modal title="The exact rules" eyebrow="STRATEGY MANIFEST" onClose={()=>setShowJson(false)}><div className="modal-body"><p>This JSON is your reviewable strategy. Its hash anchors the document you authorize.</p><pre className="code-panel">{JSON.stringify(manifest,null,2)}</pre>{!issues.length&&<div className="hash-line"><span>Manifest hash</span><code>{manifestHash(manifest)}</code></div>}<div className="modal-button-row"><button className="btn btn-white" onClick={copy}><Copy size={15}/> Copy JSON</button><button className="btn btn-primary" onClick={download}><Download size={15}/> Download</button></div></div></Modal>}
 {showCompiler&&<Modal title="Start with your own words" eyebrow="LOCAL INTENT COMPILER" onClose={()=>setShowCompiler(false)}><div className="modal-body"><p>Describe your market, condition, order size and every risk limit. Circuit turns supported instructions into a draft for you to review.</p><label className="field"><span>Your idea</span><textarea rows={6} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label>{compilerErrors.length>0&&<div className="compiler-issues" role="alert"><strong>A little more detail is needed.</strong><p>These values weren’t supplied or aren’t supported. Add them to your prompt.</p><ul>{compilerErrors.map(error=><li key={error}>{error}</li>)}</ul></div>}<div className="compiler-disclosure"><LockKeyhole size={15}/> A draft only. No wallet signature or trade.</div><button className="btn btn-primary full-width" onClick={compile}><Sparkles size={16}/> Compile my draft <ArrowRight size={16}/></button></div></Modal>}
 {activationOpen&&circuit.wallet&&market.market&&<ActivationDialog open manifest={manifest} market={market.market} wallet={circuit.wallet} onClose={()=>setActivationOpen(false)} onActivity={(title,detail,kind,hash)=>circuit.addActivity(title,detail,kind,hash)} onActivated={(id,_sub,details)=>{void circuit.activated(id,details.subscriptions,details.blockNumber,manifest).then(()=>{setActivationOpen(false);circuit.toast('Your circuit is armed on chain.','success');onActivated()}).catch(error=>circuit.toast(String(error),'error'))}}/>}
 </>
}
