import { useState } from 'react'
import { ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronDown, Code2, GitBranch, LockKeyhole, Play, Radio, ShieldCheck, Sparkles, X } from 'lucide-react'
import { Brand, Pill } from './shared'
import programProof from '../../../deployments/evidence/local-three-programs.json'
import programProofUrl from '../../../deployments/evidence/local-three-programs.json?url'
import { templateCatalog } from '../../lib/workspace'
export default function Landing({onStart}:{onStart:(template?:string)=>void}){
 const [menu,setMenu]=useState(false)
 const [threshold,setThreshold]=useState(70)
 return <div className="landing"><header className="landing-nav"><a href="#/" aria-label="Circuit home"><Brand/></a><nav className={menu?'landing-links open':'landing-links'} aria-label="Main navigation"><a href="#how-it-works" onClick={()=>setMenu(false)}>How it works</a><a href="#possibilities" onClick={()=>setMenu(false)}>Strategies</a><a href="#built-on-trust" onClick={()=>setMenu(false)}>Built on trust</a></nav><div className="landing-nav-actions"><button className="btn btn-lime btn-sm" onClick={()=>onStart()}>Launch app <ArrowUpRight size={15}/></button><button className="icon-btn mobile-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<span className="menu-lines"/>}</button></div></header>
 <main id="main-content"><section className="landing-hero"><div className="hero-copy"><Pill tone="dark"><span className="little-orbit"/> A strategy language for Event Contracts</Pill><h1>Your strategies.<br/><span>Programmable.</span></h1><p>Give Event Contracts a programmable strategy language.<br/> Compose a graph. Compile its rules. Run different programs on the same bounded Engine.</p><div className="hero-actions"><button className="btn btn-lime btn-lg" onClick={()=>onStart()}>Build your first circuit <ArrowUpRight size={19}/></button><a className="hero-secondary" href="#how-it-works"><span><Play size={13} fill="currentColor"/></span>See how it flows</a></div><div className="hero-footnote"><ShieldCheck size={15}/> Your wallet. Your boundaries. Your call.</div></div>
 <div className="hero-art" aria-label="Illustrative conditional strategy"><div className="art-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-caption"><span className="little-orbit"/> A LITTLE LOGIC. A LOT OF POSSIBILITY.</div><div className="art-card art-market"><div className="coin-icon">₿</div><div><small>THE MARKET</small><strong>Bitcoin <span>UP / DOWN</span></strong></div><Radio size={17}/></div><div className="art-line first"><i/></div><div className="art-card art-condition"><div className="art-icon"><GitBranch size={19}/></div><div><small>YOUR CONDITION</small><strong>When UP &gt; <button aria-label="Change example threshold" title="Try another threshold" onClick={()=>setThreshold(threshold===70?60:70)}>{threshold}% <ChevronDown size={13}/></button></strong></div><span className="art-check"><Check size={14}/></span></div><div className="art-line second"><i/></div><div className="art-card art-action"><div className="art-action-main"><div className="art-icon action"><ArrowDownRight size={22}/></div><div><small>YOUR ACTION</small><strong>Buy DOWN <span>within your limit</span></strong></div></div><div className="art-tail"><span>WIN → ROLL</span><span>LOSS → CHECK LIMITS</span></div></div><div className="art-tag"><LockKeyhole size={13}/> Bounded by design</div><div className="art-example">Illustrative strategy · no order is placed</div></div>
 <a className="scroll-cue" href="#how-it-works"><ArrowDown size={16}/> A calmer way to trade</a></section>
 <div className="ecosystem-strip"><span>MADE FOR ON-CHAIN EVENT MARKETS</span><div><span className="somnia-word">◉ somnia</span><span className="ecosystem-cross">×</span><span className="dream-word">dreamDEX <small>EVENT CONTRACTS</small></span></div><span className="network-caption">Currently on Shannon testnet <i/></span></div>
 <section className="landing-section how-section" id="how-it-works"><div className="section-intro"><span className="eyebrow">COMPOSE → COMPILE → EXECUTE → REACT</span><h2>A plan you can see.<br/><em>A process you can trust.</em></h2><p>No more piecing together each market window.<br/>Give your strategy a beginning, a boundary, and a next step.</p></div><div className="how-grid">{[{n:'01',Icon:GitBranch,title:'Compose a program.',body:'Add and connect market, condition, buy, outcome, roll and stop nodes. The rules belong to your graph.',label:'NODES → TYPED CONNECTIONS'},{n:'02',Icon:ShieldCheck,title:'Compile the rules.',body:'The compiler rejects unsupported connections and missing limits. Review the executable manifest and its hash before authorization.',label:'GRAPH → MANIFEST → HASH'},{n:'03',Icon:Radio,title:'Execute and react.',body:'One Engine runs each program within its approved limits. Follow real fills, settlement and successor transitions through receipts.',label:'ONE ENGINE → DIFFERENT PROGRAMS'}].map(({n,Icon,title,body,label})=><article className="how-card" key={n}><div><span className="how-number">{n}</span><Icon size={25}/></div><h3>{title}</h3><p>{body}</p><small>{label}</small></article>)}</div></section>
 <section className="landing-section possibilities" id="possibilities"><div className="section-heading-row"><div><span className="eyebrow">A STARTING POINT, NOT A BLACK BOX</span><h2>Find your kind<br/>of <em>flow.</em></h2></div><p>Same engine. Three different trading programs.<br/>Compose your own rules from each starting point.</p></div><div className="template-grid">{templateCatalog.map((t,i)=><button className={`landing-template ${t.color}`} onClick={()=>onStart(t.id)} key={t.id}><div className="template-symbol"><GitBranch size={29} style={{transform:`rotate(${i*45}deg)`}}/></div><small>{t.tag}</small><h3>{t.name}</h3><p>{t.description}</p><span>Explore this strategy <ArrowUpRight size={18}/></span></button>)}</div><div className="runtime-proof"><div><strong>{programProof.programsExecuted} programs · {programProof.engineDeployments} Engine · {programProof.settledRounds} settled rounds</strong><p>Local Anvil integration with mock markets and simulated validator dispatch.</p></div><a className="text-link" href={programProofUrl} target="_blank" rel="noreferrer">Inspect runtime proof <Code2 size={15}/></a></div></section>
 <section className="trust-section" id="built-on-trust"><div><span className="eyebrow">CONFIDENCE COMES FROM CLARITY</span><h2>Nothing hidden.<br/><em>Everything bounded.</em></h2><p>Your funds stay in your smart account. Circuit executes within the rules you approve, and each on-chain action has a receipt you can inspect.</p><a className="text-link" href="https://shannon-explorer.somnia.network/tx/0xb9561543c7839b00691ffd62e488a7e497bbefd56edda18f721ec20d37c15d91" target="_blank" rel="noreferrer">Inspect a real Circuit order <ArrowUpRight size={16}/></a></div><div className="trust-list">{[[LockKeyhole,'Your limits are part of the program.','Order size, total spending, expiry buffer and round limits are checked at execution.'],[Code2,'Clear intent. Deterministic rules.','A local intent compiler helps draft your strategy. It asks for missing limits instead of making them up.'],[Radio,'Real events. Visible outcomes.','On-chain callbacks, bounded keeper execution and verifiable settlement across market windows.']].map(([Icon,title,body])=>{const I=Icon as typeof LockKeyhole;return <article key={String(title)}><I size={22}/><div><h3>{String(title)}</h3><p>{String(body)}</p></div></article>})}</div></section>
 <section className="landing-cta"><span className="eyebrow">A LITTLE MORE INTENTION.</span><h2>A lot more <em>you.</em></h2><p>Your next strategy starts with a simple rule.</p><button className="btn btn-ink btn-lg" onClick={()=>onStart()}>Create your circuit <ArrowUpRight size={18}/></button><small>Explore without a wallet. Connect when you’re ready.</small></section></main>
 <footer className="landing-footer"><a href="#/" aria-label="Circuit home"><Brand small/></a><p>Compose → Compile → Execute → React.</p><span>Built on Somnia · Shannon testnet</span><button onClick={()=>onStart()}>Open workspace <ArrowRight size={15}/></button></footer>
 </div>
}
