import { marketWindowLabel } from '../../lib/market-windows'
import { useLayoutEffect, useRef, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { ArrowUpRight, Check, ChevronRight, GitBranch, Loader2, LockKeyhole, Radio, RotateCcw, X } from 'lucide-react'
import type { StrategyManifest } from '../../lib/strategy'
import circuitLogo from '../../../circuit_logo.png'

export function LogoMark({className='brand-symbol'}:{className?:string}){return <img className={className} src={circuitLogo} alt="" aria-hidden="true" width={64} height={64} decoding="async"/>}
export function Brand({small=false}:{small?:boolean}){return <span className={`brand ${small?'brand-small':''}`}><LogoMark/><span>circuit<span className="brand-period">.</span></span></span>}
export function Pill({children,tone='neutral',pulse=false}:{children:ReactNode;tone?:string;pulse?:boolean}){return <span className={`pill pill-${tone}`}>{pulse&&<i className="status-point"/>}{children}</span>}
export function Spinner({label='Working'}:{label?:string}){return <span className="inline-loading"><Loader2 size={15} className="spin"/>{label}</span>}
export function ExplorerLink({hash,children='View transaction'}:{hash:string;children?:ReactNode}){return <a className="text-link" href={`https://shannon-explorer.somnia.network/tx/${hash}`} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={14}/></a>}
export function Modal({title,eyebrow,children,onClose,busy=false,wide=false}:{title:string;eyebrow?:string;children:ReactNode;onClose:()=>void;busy?:boolean;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null)
 useLayoutEffect(()=>{const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus({preventScroll:true});return()=>{document.body.style.overflow=overflow;previous?.focus({preventScroll:true})}},[])
 // A completed step can remove the focused action; keep keyboard focus in the dialog.
 useLayoutEffect(()=>{if(ref.current&&!ref.current.contains(document.activeElement))ref.current.focus({preventScroll:true})})
 return createPortal(<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><div ref={ref} tabIndex={-1} className={`modal ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-label={title} onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const focusables=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),textarea,select,[tabindex="0"]');if(!focusables?.length){e.preventDefault();return}const first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><header className="modal-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div><button className="icon-btn" aria-label="Close dialog" onClick={onClose} disabled={busy}><X size={20}/></button></header>{children}</div></div>,document.body)
}
export type RuleSection='market'|'entry'|'risk'|'review'
export function StrategyFlow({manifest,onSelect,selected}:{manifest:StrategyManifest;onSelect?:(section:RuleSection)=>void;selected?:RuleSection}){
 const Node=({section,icon,title,children}:{section:RuleSection;icon:ReactNode;title:string;children:ReactNode})=><button type="button" className={`flow-node ${selected===section?'selected':''}`} onClick={()=>onSelect?.(section)} disabled={!onSelect}><span className={`flow-node-icon ${section}`}>{icon}</span><span><small>{title}</small><strong>{children}</strong></span>{onSelect&&<ChevronRight size={16}/>}</button>
 return <div className="strategy-flow"><div className="flow-start"><span/> Your strategy begins</div><Node section="market" icon={<Radio size={20}/>} title="WATCH THIS MARKET">{manifest.series.asset} <span className="soft">/ {marketWindowLabel(manifest.series.intervalSec)}</span></Node><div className="flow-connector"><span>when</span></div><Node section="entry" icon={<GitBranch size={20}/>} title="CHECK THE CONDITION">UP price {manifest.trigger.type==='LAST_FILL_PRICE_ABOVE'?'>':'<'} <em>{manifest.trigger.value}</em></Node><div className="flow-connector"><span>condition met</span><small>No match? Keep watching.</small></div><Node section="entry" icon={<ArrowUpRight size={20} className={manifest.action.type==='BUY_DOWN'?'rotate-down':''}/>} title="PLACE A BOUNDED ORDER">Buy {manifest.action.type==='BUY_UP'?'UP':'DOWN'} <span className="soft">/ max {manifest.action.maxCollateral} tUSDC</span></Node><div className="flow-connector"><span>after resolution</span></div><div className="flow-branches"><button type="button" onClick={()=>onSelect?.('risk')} disabled={!onSelect}><span className="branch-label"><Check size={13}/> ON WIN</span><strong>{manifest.action.sizing?`Increase by ${manifest.action.sizing.incrementCollateral} tUSDC`:`Roll ${manifest.resolution.onWin.rollPercent}%`}</strong><small>{manifest.action.sizing?`Start ${manifest.action.sizing.initialCollateral} · max ${manifest.action.maxCollateral} per order`:'of redeemed proceeds, within caps'}</small></button><button type="button" onClick={()=>onSelect?.('risk')} disabled={!onSelect}><span className="branch-label loss"><RotateCcw size={13}/> ON LOSS</span><strong>Count the loss</strong><small>Stop after {manifest.policy.stopAfterConsecutiveLosses} consecutive losses</small></button></div><div className="flow-connector short"/><Node section="risk" icon={<LockKeyhole size={19}/>} title="CHECK LIMITS, THEN CONTINUE">Next window <span className="soft">/ up to {manifest.policy.maxRounds} rounds</span></Node><div className="flow-end"><span/> Void rounds stay neutral. Your capital cap always applies.</div></div>
}
